### ISSUE TITLE
Add Duration Feature

### ISSUE THREAD

**Issue by deep-69bits** [iiitl/geet-hub-editor#16] opened 2022-10-03 08:46 UTC

**Comment by PrerakMathur20** [comment] 2022-10-03 14:12
KIndly add a detailed and descriptive explanation of the Issue and the feature that needs to be added for others to understand the problem better.

Moreover, the order of the process is, once the issue is created, the maintainers approve that issue as a valid one and after that assignment of the issue is done. Only after that, the assignee is supposed to start working on that issue. 

These practices are widely accepted and are the only ones appreciated in this field. Kindly follow them.

**Comment by deep-69bits** [comment] 2022-10-03 14:25
### On uploading audio  file it will show the duration in second of the audio file..

**Comment by PrerakMathur20** [comment] 2022-10-03 21:07
> KIndly add a detailed and descriptive explanation of the Issue and the feature that needs to be added for others to understand the problem better.
> 
> Moreover, the order of the process is, once the issue is created, the maintainers approve that issue as a valid one and after that assignment of the issue is done. Only after that, the assignee is supposed to start working on that issue.
> 
> These practices are widely accepted and are the only ones appreciated in this field. Kindly follow them.

Read this again, this time thoroughly.

**Comment by deep-69bits** [comment] 2022-10-05 07:02
@PrerakMathur20 
### On uploading audio file we don't get its length . I just want to make a small change to add getDuration method given by waveform object which returns the length of the audio clip in seconds. Can I??

![image](https://user-images.githubusercontent.com/96793524/193999506-f58f28fc-cf4b-4169-9e49-8408dcc717b7.gif)

**Comment by PrerakMathur20** [comment] 2022-10-19 14:28
@deep-69bits Any Updates?

**Comment by PrerakMathur20** [comment] 2022-10-23 16:05
@deep-69bits 
Unassigned due to inactivity.

**Comment by pranjalad12** [comment] 2022-10-23 16:16
@PrerakMathur20 sir, Please assign this Issue to me, Thanks.

**Closed as completed** 2022-10-23 20:16 UTC
Labels: hacktoberfest
